name = "ai-lesson-planner"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ai-lesson-planner-db"
database_id = "5fda39d8-65b0-45a6-9001-c4c7978368f1"

[vars]
ENVIRONMENT = "production"
